export const defaultTheme = {
  color: {
    mainBlue: "#3692FF",
    subBlue: "#3182F6",
    anotherBlue: "#cfe5ff",
    white: "#ffffff",
    offwhite: "#FCFCFC",
    mainIvory: "#F3F4F6",
    subIvory: "#F9FAFB",
    anotherIvory: "#E5E7EB",
    footerCopyright: "#9CA3AF",
    mainBlack: "#1F2937",
    subBlack: "#111827",
    anotherBlack: "#374151",
    mainCharcoal: "#4B5563",
    subCharcoal: "#6B7280",
    mainGrey: "#9CA3AF",
    subGrey: "#DFDFDF",
    inputBg: "#F3F4F6",
    activeColor: "#3692ff",
  },
  media: {
    small: `@media (max-width: ${743}px)`,
    medium: `@media (max-width: ${1199}px)`,
  },
};
